export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT_SUCCESS = " LOGOUT_SUCCESS";

export const CREATE_MESSAGES_LOADING = "CREATE_MESSAGES_LOADING";
export const CREATE_MESSAGES_SUCCESS = "CREATE_MESSAGE_SUCCESS";

export const CLEAR_MESSAGES_LOADING = "CLEAR_MESSAGES_LOADING";
export const CLEAR_MESSAGES_SUCCESS = "CLEAR_MESSAGES_SUCCESS";

export const CLEAR_ERRORS_LOADING = "CLEAR_ERRORS_LOADING";
export const CLEAR_ERRORS_SUCCESS = "CLEAR_ERRORS_SUCCESS";

export const GET_ERRORS = "GET_ERRORS";

export const CHECK_USER_TYPE_LOADING = "CHECK_USER_TYPE_LOADING";
export const CHECK_USER_TYPE_SUCCESS = "CHECK_USER_TYPE_SUCCESS";
export const CHECK_USER_TYPE_FAIL = "CHECK_USER_TYPE_FAIL";

export const GET_USER_DATA_LOADING = "GET_USER_DATA_LOADING";
export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const GET_USER_DATA_FAIL = "GET_USER_DATA_FAIL";

export const GET_USERS_LOADING = "GET_USERS_LOADING";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";

export const VERIFY_USER_LOADING = "VERIFY_USER_LOADING";
export const VERIFY_USER_SUCCESS = "VERIFY_USER_SUCCESS";
export const VERIFY_USER_FAIL = "VERIFY_USER_FAIL";

export const UN_VERIFY_USER_LOADING = "UN_VERIFY_USER_LOADING";
export const UN_VERIFY_USER_SUCCESS = "UN_VERIFY_USER_SUCCESS";
export const UN_VERIFY_USER_FAIL = "UN_VERIFY_USER_FAIL";

export const CREATE_BLOG_LOADING = "CREATE_BLOG_LOADING";
export const CREATE_BLOG_SUCCESS = "CREATE_BLOG_SUCCESS";
export const CREATE_BLOG_FAIL = "CREATE_BLOG_FAIL";

export const GET_IMAGE_LOADING = "GET_IMAGE_LOADING";
export const GET_IMAGE_SUCCESS = "GET_IMAGE_SUCCESS";
export const GET_IMAGE_FAIL = "GET_IMAGE_FAIL";

export const GET_PAYMENTS_LOADING = "GET_PAYMENTS_LOADING";
export const GET_PAYMENTS_SUCCESS = "GET_PAYMENTS_SUCCESS";
export const GET_PAYMENTS_FAIL = "GET_PAYMENTS_FAIL";

export const GET_BLOG_LOADING = "GET_BLOG_LOADING";
export const GET_BLOG_SUCCESS = "GET_BLOG_SUCCESS";
export const GET_BLOG_FAIL = "GET_BLOG_FAIL";

export const UPLOAD_BLOG_LOADING = "UPLOAD_BLOG_LOADING";
export const UPLOAD_BLOG_SUCCESS = "UPLOAD_BLOG_SUCCESS";
export const UPLOAD_BLOG_FAIL = "UPLOAD_BLOG_FAIL";

export const ADD_AMOUNT_LOADING = "ADD_AMOUNT_LOADING";
export const ADD_AMOUNT_SUCCESS = "ADD_AMOUNT_SUCCESS";
export const ADD_AMOUNT_FAIL = "ADD_AMOUNT_FAIL";

export const GET_NOTIFICATIONS_LOADING = "GET_NOTIFICATIONS_LOADING";
export const GET_NOTIFICATIONS_SUCCESS = "GET_NOTIFICATIONS_SUCCESS";
export const GET_NOTIFICATIONS_FAIL = "GET_NOTIFICATIONS_FAIL";

export const CURRENT_USER_LOADING = "CURRENT_USER_LOADING";
export const CURRENT_USER_SUCCESS = "CURRENT_USER_SUCCESS";
export const CURRENT_USER_FAIL = "CURRENT_USER_FAIL";

export const MAKE_USER_ADMIN_LOADING = "MAKE_USER_ADMIN_LOADING";
export const MAKE_USER_ADMIN_SUCCESS = "MAKE_USER_ADMIN_SUCCESS";
export const MAKE_USER_ADMIN_FAIL = "MAKE_USER_ADMIN_FAIL";

export const REMOVE_USER_ADMIN_LOADING = "REMOVE_USER_ADMIN_LOADING";
export const REMOVE_USER_ADMIN_SUCCESS = "REMOVE_USER_ADMIN_SUCCESS";
export const REMOVE_USER_ADMIN_FAIL = "REMOVE_USER_ADMIN_FAIL";
