export const APP_USERS = {
    REUSER: "REUSER",
    DONOR: "DONOR",
    RESELLER: "RESSELLER",
    RECEIVER: "RECEIVER",
    BUYER: "BUYER",
    ALL: "All"

}

export const PRODUCT_STATUSES = {
    
    APPROVED: "APPROVED",
    PENDING: "PENDING",
    REJECTED: "REJECTED",
    ALL: "All",
    ACCEPTED: "ACCEPTED",
    DELIVERED: "DELIVERED",
}